spring.application.name=apiRestClientCommande
server.port=7000

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=apiRestClientCommande;encrypt=false;trustServerCertificate=true;loginTimeout=10
spring.datasource.username=sa
spring.datasource.password=Password123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT (cl? valide >= 32 caract?res)
app.secret-key=FfMqFNDsj2e1SpiSOO6pNXawpV6aviai6o7xKmhqx3k=
app.expiration-time=900000

# Logs
logging.level.root=INFO
logging.level.com.tpspringboot=DEBUG
logging.level.com.tpspringboot.apirestclientcommande.User.filter=DEBUG
logging.level.com.tpspringboot.apirestclientcommande.User.configuration=DEBUG
logging.level.org.springframework.security=DEBUG