spring.application.name=apiRestClientCommande

#Tomcat configuration
server.port=7000

#Log level configuration
logging.level.root=ERROR
logging.level.com.tpspringboot=INFO
logging.level.org.springframework.boot.autoconfigure.h2=INFO
logging.level.org.springframework.boot.web.embedded.tomcat=INFO


spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=apiRestClientCommande;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Password123

spring.jpa.hibernate.ddl-auto=update
# Afficher les requêtes SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Formater les requêtes pour qu'elles soient lisibles
spring.jpa.properties.hibernate.format_sql=true

# Optionnel : voir aussi les paramètres des requêtes (valeurs)
spring.jpa.properties.hibernate.type=trace

# Securité JWT
app.secret-key=FfMqFNDsj2e1SpiSOO6pNXawpV6aviai6o7xKmhqx3k=
app.expiration-time=900000

# Logs Spring Security (le plus important)
logging.level.org.springframework.security=DEBUG

# Logs du filtre de sécurité
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

# Logs authentification
logging.level.org.springframework.security.authentication=DEBUG

# Logs autorisation
logging.level.org.springframework.security.access=DEBUG